name: SSH autodeploy

on:
  push:
    branches: [ "old-version" ]
  pull_request:
    branches: [ "old-version" ]
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Install OpenSSH
      run:  |
        sudo apt update
        sudo apt install -y openssh-client
    - name: Install OpenFortiVPN
      run: |
        sudo apt update
        sudo apt install -y openfortivpn
    - name: Configure and connect to VPN
      run: |
        openfortivpn ${{ secrets.VPN_GATEWAY_HOST }}:${{ secrets.VPN_GATEWAY_PORT }} -u ${{ secrets.VPN_USERNAME }} -p ${{ secrets.VPN_PASSWORD }} --trusted-cert ${{ secrets.VPN_TRUSTED_CERT }}
    - name: Configure and connect to SSH + Execute commands (Sync files)
      run: |
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ vars.SSH_PORT }}
          script: whoami
