name: SSH autodeploy

on:
  push:
    branches: [ "old-version" ]
  pull_request:
    branches: [ "old-version" ]
  workflow_dispatch:

jobs:
  # web-deploy:
  #   name: Deploy
  #   steps:
  #   - name: Checkout the repo
  #     uses: actions/checkout@v4
  # TODO: fix openfortivpn method, because it blocks taskflow
  # sudo openfortivpn ${{ secrets.VPN_GATEWAY_HOST }}:${{ secrets.VPN_GATEWAY_PORT }} -u ${{ secrets.VPN_USERNAME }} -p ${{ secrets.VPN_PASSWORD }} --trusted-cert ${{ secrets.VPN_TRUSTED_CERT }} &
  
  vpn:
    name: VPN
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenFortiVPN and OpenConnect
        run: |
          sudo apt update
          sudo apt install -y openfortivpn openconnect
      - name: Configure and connect to VPN + Check connection to VPN
        run: |
          echo "${{ secrets.VPN_PASSWORD }}" | openconnect ${{ secrets.VPN_GATEWAY_HOST }}:${{ secrets.VPN_GATEWAY_PORT }} -u ${{ secrets.VPN_USERNAME }} --passwd-on-stdin --no-cert-check --protocol=fortinet --background & sleep 30
          ping -c4 ${{ secrets.SSH_SERVER }}
  ssh:
    needs: vpn
    name: SSH
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenSSH
        run: |
          sudo apt update
          sudo apt install -y openssh-client
      - name: Configure and connect to SSH + Execute commands (Sync files)
        run: |
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.SSH_SERVER }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ vars.SSH_PORT }}
            script: whoami
